services:
  konnect-gateway:
    image: kong/kong-gateway:3.10
    container_name: konnect-gateway
    environment:
      KONG_ROLE: data_plane
      KONG_DATABASE: off
      KONG_VITALS: off
      KONG_CLUSTER_MTLS: pki
      KONG_CLUSTER_CONTROL_PLANE: ${KONNECT_ID}.us.cp0.konghq.com:443
      KONG_CLUSTER_SERVER_NAME: ${KONNECT_ID}.us.cp0.konghq.com
      KONG_CLUSTER_TELEMETRY_ENDPOINT: ${KONNECT_ID}.us.tp0.konghq.com:443
      KONG_CLUSTER_TELEMETRY_SERVER_NAME: ${KONNECT_ID}.us.tp0.konghq.com
      KONG_CLUSTER_CERT: ${KONG_CLUSTER_CERT}
      KONG_CLUSTER_CERT_KEY: ${KONG_CLUSTER_CERT_KEY}
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
      KONG_KONNECT_MODE: on
      KONG_CLUSTER_DP_LABELS: type:docker-macOsArmOS
      KONG_ROUTER_FLAVOR: expressions
    ports:
      - 8000:8000
      - 8443:8443
