_format_version: "3.0"
_transform: true

services:
  - host: httpbin.konghq.com
    name: example_service
    port: 80
    protocol: http
    routes:
      - name: example_route
        paths:
          - /mock
        strip_path: true
  - host: api.shukawam.me
    name: gin_service
    port: 8080
    protocol: http
    routes:
      - name: gin_route
        paths:
          - /ping
          - /greet
        strip_path: true
