x-kong-default: &default
  networks:
    - kong-net
  restart: on-failure
x-kong-env: &kong-env
  KONG_DATABASE: postgres
  KONG_PG_HOST: kong-database
  KONG_PG_PASSWORD: kong
  KONG_PASSWORD: kong

networks:
  kong-net:

services:
  api:
    <<: *default
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: api
    hostname: api.shukawam.me
    ports:
      - 8080:8080
  kong-database:
    <<: *default
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 30s
      timeout: 30s
      retries: 3
  kong-migrations:
    <<: *default
    image: &kong-gateway-image kong/kong-gateway:3.10.0.1
    container_name: kong-migrations
    depends_on:
      - kong-database
    command: kong migrations bootstrap
    environment:
      <<: *kong-env
  kong-gateway:
    <<: *default
    image: *kong-gateway-image
    container_name: kong-gateway
    depends_on:
      - kong-migrations
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    environment:
      <<: *kong-env
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_HOST: http://localhost:8002
      # Kong Gateway License Key, if you have
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA:-}
